groups:
  ics-it:
    - ics-it
  admin:
    - petr.pokusaev@ics-it.ru
    - andrey.lastochkin@ics-it.ru
    - alexander.machulin@ics-it.ru
    - ekaterina.pavlova@ics-it.ru
  gramax:
    - stanislav.yargunkin@ics-it.ru
    - stanislav.petrov@ics-it.ru
